name: 'crane-plus'
description: '一个支持多模式的镜像同步工具'

inputs:
  src:
    description: '源镜像'
    required: true
  dst:
    description: '目标仓库前缀'
    required: true
  platform:
    description: '目标架构'
    required: false
  max_concurrent:
    description: '最大并发数'
    default: '4'

runs:
  using: "composite"
  steps:
    # 这一步会自动把 crane 安装到 Runner 的系统 PATH 里
    - name: Setup Crane
      uses: imjasonh/setup-crane@v0.7
      
    - name: Run entrypoint
      shell: bash
      run: bash ${{ github.action_path }}/entrypoint.sh
      env:
        INPUT_SRC: ${{ inputs.src }}
        INPUT_DST: ${{ inputs.dst }}
        INPUT_PLATFORM: ${{ inputs.platform }}
        INPUT_MAX_CONCURRENT: ${{ inputs.max_concurrent }}
